Repository 5minds/GDrive-Tools, pull requests merged in 2019-11, with the labels that each got.

#8 📝 Add a Readme
  README.md
Labels: documentation

#9 ✨ Add a Method to Move a Document
  src/gdrive_tools.py
  testdoc.py
Labels: enhancement

#10 🐛Fix Exception when Creating a Document in the Root Directory of the Drive
  src/gdrive_tools.py
  testdoc.py
Labels: bug

#11 📝 Add a Simple Example Script
  example.py
  requirements.txt
Labels: documentation

#12 ✨ Read the Drive Name from the Path
  example.py
  src/gdrive_tools.py
Labels: enhancement

#13 ✨ Create a Wrapper Class for the Google Authentication
  README.md
  example.py
  src/google_auth.py
Labels: enhancement

#14 🚚 Refactor the Project Structure
  example.py
  gdrive_tools/__init__.py
  gdrive_tools/gdrive_tools.py
  gdrive_tools/google_auth.py
  gdrive_tools/google_filetypes.py
Labels: enhancement

#16 Add the SCOPES for using the GDrive-API
  README.md
Labels: documentation

#17 📝 Update the Imports on the Readme and the Example Script
  README.md
  example.py
Labels: documentation

#18 ✨Return the Id of a Created Document
  gdrive_tools/gdrive_tools.py
Labels: enhancement

#19 🐛 Fix not Installed Subdependencies
  setup.py
Labels: bug

#15 👷‍♂️ Add Jenkinsfile
  Jenkinsfile
  LICENSE
  example.py
Labels: ci

#20 📝 Add Additional Package Information
  setup.py
Labels: documentation
